"""Añadir campos de antigüedad a Propiedad

Revision ID: 448629732ffa
Revises: 6f2f850bcbef
Create Date: 2025-07-28 08:51:47.145135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448629732ffa'
down_revision = '6f2f850bcbef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antiguedad_tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('antiguedad_anos', sa.Integer(), nullable=True))
        batch_op.drop_column('antiguedad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antiguedad', sa.INTEGER(), nullable=True))
        batch_op.drop_column('antiguedad_anos')
        batch_op.drop_column('antiguedad_tipo')

    # ### end Alembic commands ###
