"""Initial migration for all models

Revision ID: 608a1bafd200
Revises: 
Create Date: 2025-07-11 15:43:16.323765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608a1bafd200'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propiedad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('estado_propiedad', sa.String(length=50), nullable=False),
    sa.Column('num_habitaciones', sa.Integer(), nullable=True),
    sa.Column('num_banos', sa.Integer(), nullable=True),
    sa.Column('num_medios_banos', sa.Integer(), nullable=True),
    sa.Column('num_estacionamientos', sa.Integer(), nullable=True),
    sa.Column('area_construccion_metros_cuadrados', sa.Float(), nullable=True),
    sa.Column('area_terreno_metros_cuadrados', sa.Float(), nullable=True),
    sa.Column('antiguedad', sa.Integer(), nullable=True),
    sa.Column('cuota_mantenimiento', sa.Float(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('imagen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=100), nullable=False),
    sa.Column('propiedad_id', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagen')
    op.drop_table('user')
    op.drop_table('propiedad')
    # ### end Alembic commands ###
