"""Add path column to PropertyImage

Revision ID: 6f2f850bcbef
Revises: 7ca6e5212d55
Create Date: 2025-07-26 19:40:06.101851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2f850bcbef'
down_revision = '7ca6e5212d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_image', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
