"""Añadir campo youtube_video_url a Property

Revision ID: ea37419d9aff
Revises: 448629732ffa
Create Date: 2025-07-29 06:53:01.850997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea37419d9aff'
down_revision = '448629732ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_video_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('youtube_video_url')

    # ### end Alembic commands ###
