"""Initial database creation with all models

Revision ID: fe9fa3a17b5f
Revises: 
Create Date: 2025-07-21 15:46:32.547760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9fa3a17b5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=False),
    sa.Column('municipio', sa.String(length=50), nullable=False),
    sa.Column('estado_propiedad', sa.String(length=50), nullable=False),
    sa.Column('tipo_propiedad', sa.String(length=50), nullable=False),
    sa.Column('num_habitaciones', sa.Integer(), nullable=True),
    sa.Column('num_banos', sa.Integer(), nullable=True),
    sa.Column('num_medios_banos', sa.Integer(), nullable=True),
    sa.Column('num_estacionamientos', sa.Integer(), nullable=True),
    sa.Column('area_terreno_metros_cuadrados', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('area_construccion_metros_cuadrados', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cuota_mantenimiento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False),
    sa.Column('agente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_image')
    op.drop_table('property')
    op.drop_table('user')
    # ### end Alembic commands ###
